name: LyricistSample
options:
  bundleIdPrefix: cafe.adriel.lyricist.sample
settings:

  CODE_SIGN_IDENTITY: "iPhone Developer"
  CODE_SIGN_STYLE: Automatic
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "4"
  SDKROOT: iphoneos
targets:
  LyricistSample:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    info:
      path: plists/Ios/Info.plist
      properties:
        UILaunchStoryboardName: LyricistSample
    settings:
      LIBRARY_SEARCH_PATHS: "$(inherited)"
      ENABLE_BITCODE: "YES"
      ONLY_ACTIVE_ARCH: "NO"
      VALID_ARCHS: "arm64"
    sources:
      - path: src
        excludes:
          - "**/.gitkeep"
    preBuildScripts:
      - name: Build KMP
        script: |
          cd ../
          ./gradlew :sample-multiplatform:embedAndSignAppleFrameworkForXcode
    dependencies:
      - framework: "../sample-multiplatform/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)/ComposeShared.framework"